- name: setting up a bastion host
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: getting variable
      include_vars: vars/output_vars

    - name: getting variable
      include_vars: vars/bastion_vars

    - name: generating key-pair for bastion-host
      ec2_key:
        name: bastionkey
        region: "{{Region}}"
      register: keyout

    - debug:
        var: keyout

    - name: saving private key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./bastionhost.pem
      when: keyout.changed

    - name: creating bastion-host security group
      ec2_group:
        name: Bastionhost-SG
        description: security group for bastion host
        vpc_id: "{{vpc_id}}"
        region: "{{Region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}" 
      register: BastionSG_out

    - name: creating a bastion host
      ec2_instance:
        key_name: bastionkey
        instance_type: t2.micro
        image_id: "{{ AMI }}"
        region: "{{ Region }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: bastion host
          Project: Ansible Project
          Owner: Mayank
        exact_count: 1
        count_tag:
          Name: bastion host
          Project: Ansible Project
          Owner: Mayank
        group_id: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1 }}"
      register: Bastionhost_out
    
        