- name: ansible playbook for keypair
  hosts: localhost
  gather_facts: false
  tasks:
    - name: creating a keypair
      ec2_key: 
        name: playbook
        region: ap-south-1
      register: keyout

    - debug:
        var: keyout

    - name: storing the key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./playbook.pem
      when: keyout.changed == true  